// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0q39_D6PoWhYfXr8pOVQ6PEYUslCO19s',
    appId: '1:1068617616106:web:9d75357e7a33ee6b156593',
    messagingSenderId: '1068617616106',
    projectId: 'todo-app-1b9e2',
    authDomain: 'todo-app-1b9e2.firebaseapp.com',
    storageBucket: 'todo-app-1b9e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATyBx6L0P1hqHpcqxPrPCGLt75l-Yj9EE',
    appId: '1:1068617616106:android:7221a0f347c40bca156593',
    messagingSenderId: '1068617616106',
    projectId: 'todo-app-1b9e2',
    storageBucket: 'todo-app-1b9e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqwvPDQ3gzuXyuONbZoHhrTZMFG0mQ7mw',
    appId: '1:1068617616106:ios:9dcb9d440315be2e156593',
    messagingSenderId: '1068617616106',
    projectId: 'todo-app-1b9e2',
    storageBucket: 'todo-app-1b9e2.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqwvPDQ3gzuXyuONbZoHhrTZMFG0mQ7mw',
    appId: '1:1068617616106:ios:9dcb9d440315be2e156593',
    messagingSenderId: '1068617616106',
    projectId: 'todo-app-1b9e2',
    storageBucket: 'todo-app-1b9e2.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0q39_D6PoWhYfXr8pOVQ6PEYUslCO19s',
    appId: '1:1068617616106:web:b50ac9a31d6499f8156593',
    messagingSenderId: '1068617616106',
    projectId: 'todo-app-1b9e2',
    authDomain: 'todo-app-1b9e2.firebaseapp.com',
    storageBucket: 'todo-app-1b9e2.appspot.com',
  );
}
